### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by montyclt** [jussi-kalliokoski/http.js#23]
I get this error where I load http.js:

`Uncaught ReferenceError: _ is not defined
    at http.js:217
    at http.js:228`

And where I try use, I get the next error:

`Uncaught TypeError: Http.get is not a function`

**Comment by jussi-kalliokoski** [comment]
Yes, that is caused by a missing dependency on either [lodash](https://lodash.com) or [underscore](http://underscorejs.org). Anyway, http.js is no longer maintained and I suggest you take a look at using the standard [Fetch API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) instead, possibly with a [polyfill](https://github.com/github/fetch) if you need to support older browsers.

**Comment by montyclt** [comment]
Thanksyou! I will use Fetch API.
